const landingUrl = 'https://innovation-guide-box.lovable.app/';
const state = { role: 'user', page: 'overview' };

const navUser = [
  ['WORKSPACE'],
  ['overview','⌂','Overview'],['sites','◫','Sites & assets'],['forecast','⌁','Forecasting'],['diagnostics','◎','Diagnostics','4'],['maintenance','✓','Maintenance','12'],
  ['INTELLIGENCE'],
  ['iot','⌘','IoT sensors'],['expert','✦','Virtual energy expert'],['advisor','△','Installation advisor'],['reports','▤','Reports'],
  ['ACCOUNT'],
  ['settings','⚙','Settings']
];
const navAdmin = [
  ['ADMINISTRATION'],
  ['admin-overview','⌂','Admin overview'],['organizations','◫','Organizations'],['users','♙','Users & roles'],['assets','◇','Asset registry'],['integrations','⇄','Data integrations'],
  ['AI & OPERATIONS'],
  ['models','✦','AI models'],['sensor-fleet','⌘','Sensor fleet'],['alerts','!','Alert policies'],['system-health','◉','System health'],
  ['GOVERNANCE'],
  ['billing','$','Plans & billing'],['audit','▤','Audit log'],['admin-settings','⚙','Platform settings']
];

const kpi = (label,value,delta,icon='↗',tone='up') => `<div class="kpi-card"><div class="kpi-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><strong>${value}</strong><span class="delta ${tone}">${delta}</span></div>`;
const pageHead = (eyebrow,title,sub,actions='') => `<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${sub}</p></div><div class="head-actions">${actions}</div></div>`;
const buttons = `<button class="secondary-btn" onclick="toast('Report export prepared')">Export report</button><button class="primary-btn" onclick="toast('Add-site workflow opened')">+ Add site</button>`;
const chart = () => `<div class="chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1a8f5b" stop-opacity=".18"/><stop offset="1" stop-color="#1a8f5b" stop-opacity="0"/></linearGradient></defs><path d="M0,185 C35,182 55,172 85,158 S140,96 180,91 S230,56 270,58 S325,35 365,48 S420,92 455,83 S520,57 550,75 S615,118 645,105 S675,92 700,98 L700,220 L0,220Z" fill="url(#area)"/><path d="M0,185 C35,182 55,172 85,158 S140,96 180,91 S230,56 270,58 S325,35 365,48 S420,92 455,83 S520,57 550,75 S615,118 645,105 S675,92 700,98" fill="none" stroke="#1a8f5b" stroke-width="3"/><path d="M0,190 C45,181 66,162 100,150 S145,109 182,98 S235,66 275,63 S320,46 365,55 S417,85 460,78 S515,64 550,71 S605,108 650,99 S680,87 700,93" fill="none" stroke="#9caaa1" stroke-width="2" stroke-dasharray="7 6"/></svg></div><div class="chart-labels"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>24:00</span></div><div class="legend"><span>Actual generation</span><span>AI forecast</span></div>`;

const alertRows = () => `
<div class="alert-list">
  <div class="alert-row"><span class="alert-icon">☀</span><div><strong>String 4B underperforming</strong><small>Samarkand Solar · likely soiling · 9 min ago</small></div><span class="severity high">HIGH</span></div>
  <div class="alert-row"><span class="alert-icon">↻</span><div><strong>T-07 power-curve deviation</strong><small>Navoi Wind · inspect yaw alignment · 24 min ago</small></div><span class="severity medium">MEDIUM</span></div>
  <div class="alert-row"><span class="alert-icon">▣</span><div><strong>Battery temperature elevated</strong><small>Tashkent Hybrid · BMS pack 02 · 41 min ago</small></div><span class="severity medium">MEDIUM</span></div>
  <div class="alert-row"><span class="alert-icon">◌</span><div><strong>Sensor S1-009 battery low</strong><small>Bukhara Rooftop · service next visit</small></div><span class="severity low">LOW</span></div>
</div>`;

const siteRows = () => `<div class="site-list">
  <div class="site-row"><span class="site-type">☀</span><div><strong>Samarkand Solar One</strong><small>Solar PV · 42 MW · 99.7% online</small><div class="progress"><i style="width:96%"></i></div></div><div class="power"><strong>31.8 MW</strong><small>PR 94.2%</small></div></div>
  <div class="site-row"><span class="site-type">↻</span><div><strong>Navoi Wind North</strong><small>Wind · 80 MW · 98.9% online</small><div class="progress"><i style="width:89%"></i></div></div><div class="power"><strong>54.4 MW</strong><small>PR 91.8%</small></div></div>
  <div class="site-row"><span class="site-type">▣</span><div><strong>Tashkent Hybrid</strong><small>Solar + BESS · 24 MW · 100% online</small><div class="progress"><i style="width:98%"></i></div></div><div class="power"><strong>18.6 MW</strong><small>PR 95.1%</small></div></div>
  <div class="site-row"><span class="site-type">⌂</span><div><strong>Bukhara Rooftop Portfolio</strong><small>Commercial solar · 6.2 MW · 99.4% online</small><div class="progress"><i style="width:92%"></i></div></div><div class="power"><strong>4.7 MW</strong><small>PR 92.7%</small></div></div>
</div>`;

function overview(){return `${pageHead('PORTFOLIO INTELLIGENCE','Good morning, Khojiakbar','Your renewable-energy portfolio is healthy. Four items need attention today.',buttons)}
<div class="kpi-grid">${kpi('Online capacity','152.2 MW','↑ 2.1% this month','⚡')}${kpi('Performance ratio','94.1%','↑ 1.4% vs last week','◎')}${kpi('Availability','99.6%','Within SLA target','◉')}${kpi('Recovered energy','182 MWh','↑ 21 MWh this month','↗')}</div>
<div class="grid-2"><div class="card"><div class="card-head"><div><h3>Generation vs AI forecast</h3><p>Portfolio output · today</p></div><div class="pill-tabs"><button class="active">24h</button><button>7d</button><button>30d</button></div></div>${chart()}</div><div class="card"><div class="card-head"><div><h3>Priority alerts</h3><p>AI-ranked by energy and revenue impact</p></div><button class="secondary-btn" onclick="setPage('diagnostics')">View all</button></div>${alertRows()}</div></div>
<div class="grid-2"><div class="card"><div class="card-head"><div><h3>Sites & asset health</h3><p>Live fleet status</p></div><button class="secondary-btn" onclick="setPage('sites')">All sites</button></div>${siteRows()}</div><div class="card expert-card"><div class="card-head"><div><h3>Virtual energy expert</h3><p>Evidence-backed intelligence across your portfolio</p></div><span class="ai-badge">✦ GEAI AI</span></div><div class="expert-message"><strong>Morning briefing:</strong> Samarkand Solar is producing 3.8% below its weather-adjusted expectation. The strongest evidence points to soiling on strings 4A–4D. Cleaning before Friday is projected to recover ~1.3 MWh/day. Navoi Wind T-07 also warrants yaw inspection within 5 days.</div><div class="expert-input"><input placeholder="Ask GEAI about your assets…"><button onclick="toast('AI query submitted')">Ask</button></div></div></div>`}

function sites(){return `${pageHead('ASSET OPERATIONS','Sites & assets','Monitor every solar, wind, storage, and hybrid asset from one data model.',`<button class="secondary-btn">Import assets</button><button class="primary-btn" onclick="toast('New asset wizard opened')">+ Add asset</button>`)}<div class="grid-2"><div class="card"><div class="card-head"><div><h3>Portfolio map</h3><p>4 operational sites · Uzbekistan</p></div><span class="tag">152.2 MW online</span></div><div class="map-placeholder"><span class="map-pin" style="left:34%;top:49%"></span><span class="map-pin" style="left:50%;top:34%"></span><span class="map-pin" style="left:67%;top:52%"></span><span class="map-pin" style="left:44%;top:67%"></span></div></div><div class="card"><div class="card-head"><div><h3>Fleet health</h3><p>Weather-adjusted operating condition</p></div></div><div class="health-ring"></div><div style="text-align:center"><strong>Healthy portfolio</strong><p class="muted" style="font-size:10px">3 assets healthy · 1 needs attention</p></div></div></div><div class="card" style="margin-top:14px"><div class="toolbar"><input class="search" placeholder="Search sites, assets, serial numbers…"><select class="filter"><option>All asset types</option><option>Solar</option><option>Wind</option><option>Storage</option></select><select class="filter"><option>All statuses</option><option>Healthy</option><option>Attention</option></select></div>${assetTable()}</div>`}
function assetTable(){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Site</th><th>Type</th><th>Capacity</th><th>Current output</th><th>Performance ratio</th><th>Availability</th><th>Status</th></tr></thead><tbody><tr><td class="name-cell">Samarkand Solar One</td><td>Solar PV</td><td>42.0 MW</td><td>31.8 MW</td><td>94.2%</td><td>99.7%</td><td><span class="tag orange">Attention</span></td></tr><tr><td class="name-cell">Navoi Wind North</td><td>Wind</td><td>80.0 MW</td><td>54.4 MW</td><td>91.8%</td><td>98.9%</td><td><span class="tag">Healthy</span></td></tr><tr><td class="name-cell">Tashkent Hybrid</td><td>Solar + BESS</td><td>24.0 MW</td><td>18.6 MW</td><td>95.1%</td><td>100%</td><td><span class="tag">Healthy</span></td></tr><tr><td class="name-cell">Bukhara Rooftop Portfolio</td><td>Commercial PV</td><td>6.2 MW</td><td>4.7 MW</td><td>92.7%</td><td>99.4%</td><td><span class="tag">Healthy</span></td></tr></tbody></table></div>`}

function forecast(){return `${pageHead('PREDICT','Generation forecasting','Weather intelligence + asset physics for hourly, daily, and portfolio forecasts.',`<button class="secondary-btn">Forecast settings</button><button class="primary-btn" onclick="toast('Forecast exported')">Export forecast</button>`)}<div class="kpi-grid">${kpi('Today forecast','2.84 GWh','97.2% confidence','☀')}${kpi('Tomorrow forecast','2.71 GWh','Cloud cover +14%','◌','warn')}${kpi('7-day expected','18.9 GWh','↑ 3.2% vs prior week','⌁')}${kpi('Forecast MAE','3.7%','↓ 0.6 pp this month','◎')}</div><div class="card" style="margin-top:14px"><div class="card-head"><div><h3>Portfolio forecast · next 24 hours</h3><p>P50 expected production with weather-adjusted confidence interval</p></div><div class="pill-tabs"><button class="active">Energy</button><button>Revenue</button><button>Weather</button></div></div>${chart()}</div><div class="grid-3"><div class="card"><div class="card-head"><h3>Solar resource</h3><span class="tag">Good</span></div><strong style="font-size:28px">5.8</strong> <small class="muted">kWh/m²/day</small><p class="muted" style="font-size:10px">Peak irradiance expected 12:20–13:40.</p></div><div class="card"><div class="card-head"><h3>Wind resource</h3><span class="tag">Strong</span></div><strong style="font-size:28px">8.7</strong> <small class="muted">m/s avg</small><p class="muted" style="font-size:10px">Favorable production window after 17:00.</p></div><div class="card"><div class="card-head"><h3>Weather risk</h3><span class="tag orange">Moderate</span></div><strong style="font-size:28px">31%</strong> <small class="muted">dust probability</small><p class="muted" style="font-size:10px">Possible soiling impact in western sites.</p></div></div>`}

function diagnostics(){return `${pageHead('DIAGNOSE','AI diagnostics','Compare actual vs expected performance and surface hidden losses before they become expensive.',`<button class="secondary-btn">Detection rules</button><button class="primary-btn">+ Create investigation</button>`)}<div class="kpi-grid">${kpi('Open anomalies','4','2 require action','!','warn')}${kpi('Potential loss','3.6 MWh/day','€218/day estimated','$','warn')}${kpi('Detection precision','96.8%','↑ 1.2 pp this month','◎')}${kpi('Mean detection time','8.4 min','↓ 2.1 min','↯')}</div><div class="grid-2"><div class="card"><div class="card-head"><div><h3>Active anomalies</h3><p>Ranked by expected energy loss</p></div></div>${alertRows()}</div><div class="card"><div class="card-head"><div><h3>AI diagnosis</h3><p>Samarkand Solar · String group 4</p></div><span class="tag orange">84% confidence</span></div><div class="expert-message" style="background:#f4f7f5;color:#243c2f;border-color:#e0e8e3"><strong style="color:#137046">Likely cause: panel soiling.</strong><br><br>Observed output is 7.1% below the physics-aware expected curve while irradiance and inverter temperature remain normal. Neighboring strings do not show the same loss pattern.<br><br><b>Recommendation:</b> clean strings 4A–4D before Friday. Estimated recovery: 1.3 MWh/day.</div><button class="primary-btn wide" style="margin-top:10px" onclick="setPage('maintenance')">Create work order</button></div></div>`}
function maintenance(){return genericTablePage('OPTIMIZE','Maintenance intelligence','Turn AI findings into prioritized, trackable work orders.','Work orders',`<tr><td class="name-cell">WO-1042</td><td>Clean strings 4A–4D</td><td>Samarkand Solar</td><td><span class="tag red">High</span></td><td>1.3 MWh/day</td><td>12 Aug</td><td><span class="tag orange">Assigned</span></td></tr><tr><td class="name-cell">WO-1041</td><td>Inspect T-07 yaw alignment</td><td>Navoi Wind</td><td><span class="tag orange">Medium</span></td><td>0.9 MWh/day</td><td>15 Aug</td><td><span class="tag grey">Open</span></td></tr><tr><td class="name-cell">WO-1037</td><td>Replace IoT sensor battery</td><td>Bukhara Rooftop</td><td><span class="tag grey">Low</span></td><td>—</td><td>22 Aug</td><td><span class="tag">Scheduled</span></td></tr>`,['ID','Task','Site','Priority','Impact','Due','Status']);}
function genericTablePage(eyebrow,title,sub,tableTitle,rows,cols){return `${pageHead(eyebrow,title,sub,`<button class="secondary-btn">Export</button><button class="primary-btn">+ New</button>`)}<div class="card"><div class="card-head"><div><h3>${tableTitle}</h3><p>Live operational data</p></div></div><div class="toolbar"><input class="search" placeholder="Search…"><select class="filter"><option>All statuses</option></select></div><div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></div>`}
function iot(){return `${pageHead('GROUND-TRUTH DATA','IoT sensor network','Environmental measurements directly beside your renewable-energy assets.',`<button class="secondary-btn">Gateway config</button><button class="primary-btn">+ Register sensor</button>`)}<div class="kpi-grid">${kpi('Sensors online','126 / 128','98.4% connectivity','⌘')}${kpi('Messages today','2.18M','MQTT ingestion healthy','⇄')}${kpi('Avg. battery','84%','Adaptive sampling active','◉')}${kpi('Data freshness','4.2 sec','Within 5 sec target','↯')}</div><div class="grid-2"><div class="card"><div class="card-head"><div><h3>GEAI-S1 · Samarkand Solar</h3><p>Sensor S1-014 · streaming · 5s cadence</p></div><span class="tag">Online</span></div><div class="sensor-grid"><div class="sensor"><span>Ambient temp.</span><strong>31.4°C</strong><small>normal</small></div><div class="sensor"><span>Panel temp.</span><strong>47.8°C</strong><small>normal</small></div><div class="sensor"><span>Illuminance</span><strong>82.6 klx</strong><small>+4.2%</small></div><div class="sensor"><span>Humidity</span><strong>34%</strong><small>normal</small></div><div class="sensor"><span>Dust / PM</span><strong>41 µg/m³</strong><small style="color:#b87816">elevated</small></div><div class="sensor"><span>Wind speed</span><strong>4.8 m/s</strong><small>stable</small></div><div class="sensor"><span>Rainfall</span><strong>0.0 mm</strong><small>24h</small></div><div class="sensor"><span>Battery</span><strong>91%</strong><small>healthy</small></div></div></div><div class="card"><div class="card-head"><div><h3>Connectivity</h3><p>Protocol and gateway health</p></div></div><div class="setting-row"><div><strong>MQTT broker</strong><small>geai-prod-01 · TLS</small></div><span class="tag">Connected</span></div><div class="setting-row"><div><strong>Modbus gateway</strong><small>Samarkand edge gateway</small></div><span class="tag">Connected</span></div><div class="setting-row"><div><strong>OPC UA bridge</strong><small>Navoi SCADA</small></div><span class="tag">Connected</span></div><div class="setting-row"><div><strong>Weather API</strong><small>Multi-source weather fusion</small></div><span class="tag">Healthy</span></div></div></div>`}
function expert(){return `${pageHead('GEAI COPILOT','Virtual energy expert','Ask natural-language questions across assets, forecasts, maintenance, weather, and financial data.','')}<div class="grid-2"><div class="card expert-card" style="min-height:480px"><div class="card-head"><div><h3>Ask GEAI</h3><p>Grounded in your live operational data</p></div><span class="ai-badge">✦ AI online</span></div><div class="expert-message"><strong>You:</strong> Why is Samarkand Solar underperforming today?</div><div class="expert-message" style="margin-top:9px"><strong>GEAI:</strong> Output is 3.8% below weather-adjusted expectation. The loss is concentrated in strings 4A–4D and correlates with elevated particulate measurements from nearby GEAI-S1 sensors. Inverter temperature and grid curtailment are normal, making soiling the most likely cause. Cleaning those strings is estimated to recover 1.3 MWh/day.</div><div class="expert-input" style="margin-top:18px"><input placeholder="Ask about output, faults, weather, revenue…"><button onclick="toast('Question sent to GEAI AI')">Ask</button></div></div><div class="card"><div class="card-head"><div><h3>Suggested questions</h3><p>Start with a common operational workflow</p></div></div>${['Which site lost the most energy this week?','What should my team inspect today?','Compare forecast accuracy across all sites.','How much revenue did AI recommendations recover?','Which sensors are reporting abnormal conditions?'].map(q=>`<button class="secondary-btn wide" style="text-align:left;margin:4px 0" onclick="toast('Question loaded')">${q}</button>`).join('')}</div></div>`}
function advisor(){return `${pageHead('PLAN','Installation advisor','Model solar, storage, and hybrid systems before installation.','<button class="primary-btn">+ New assessment</button>')}<div class="grid-2"><div class="card"><div class="card-head"><div><h3>Project inputs</h3><p>Example commercial rooftop assessment</p></div></div><div class="setting-row"><div><strong>Location</strong><small>Tashkent, Uzbekistan</small></div><span class="tag grey">41.30° N</span></div><div class="setting-row"><div><strong>Available roof area</strong><small>South-west orientation · 15° tilt</small></div><strong>1,240 m²</strong></div><div class="setting-row"><div><strong>Annual consumption</strong><small>Imported from 12-month meter history</small></div><strong>318 MWh</strong></div><div class="setting-row"><div><strong>Battery option</strong><small>LFP · grid-connected</small></div><strong>250 kWh</strong></div><button class="primary-btn wide" style="margin-top:16px" onclick="toast('Optimization started')">Run AI optimization</button></div><div class="card"><div class="card-head"><div><h3>GEAI recommendation</h3><p>Physics + weather + financial optimization</p></div><span class="tag">Optimal</span></div><div class="sensor-grid"><div class="sensor"><span>System size</span><strong>186 kWp</strong></div><div class="sensor"><span>Annual yield</span><strong>289 MWh</strong></div><div class="sensor"><span>Self-consumption</span><strong>74%</strong></div><div class="sensor"><span>Payback</span><strong>5.9 yrs</strong></div><div class="sensor"><span>CO₂ avoided</span><strong>128 t/yr</strong></div><div class="sensor"><span>Energy savings</span><strong>€31.4k/yr</strong></div></div></div></div>`}
function reports(){return genericTablePage('REPORTING','Reports & exports','Generate operational, technical, financial, and ESG reports for any site or portfolio.','Available reports',`<tr><td class="name-cell">July 2026 Portfolio Performance</td><td>Portfolio</td><td>Performance</td><td>31 Jul 2026</td><td><span class="tag">Ready</span></td></tr><tr><td class="name-cell">Samarkand Loss Attribution</td><td>Samarkand Solar</td><td>Diagnostics</td><td>8 Aug 2026</td><td><span class="tag">Ready</span></td></tr><tr><td class="name-cell">Q2 ESG & CO₂ Impact</td><td>Portfolio</td><td>ESG</td><td>30 Jun 2026</td><td><span class="tag">Ready</span></td></tr>`,['Report','Scope','Type','Generated','Status']);}
function settings(){return `${pageHead('ACCOUNT','Workspace settings','Manage your profile, notifications, units, and workspace preferences.','')}<div class="grid-2"><div class="card"><div class="card-head"><h3>Notifications</h3></div>${setting('Critical anomaly alerts','Email + in-app notifications',true)}${setting('Daily AI briefing','07:00 local time',true)}${setting('Maintenance reminders','24 hours before due date',true)}${setting('Weekly performance digest','Monday at 08:00',false)}</div><div class="card"><div class="card-head"><h3>Preferences</h3></div>${setting('Metric units','MW, MWh, °C, m/s',true)}${setting('Automatic timezone','Europe/Helsinki',true)}${setting('Dark mode','Use system preference',false)}${setting('AI explanation detail','Show evidence and confidence',true)}</div></div>`}
const setting=(a,b,on)=>`<div class="setting-row"><div><strong>${a}</strong><small>${b}</small></div><span class="switch ${on?'on':''}" onclick="this.classList.toggle('on')"></span></div>`;

function adminOverview(){return `${pageHead('PLATFORM ADMINISTRATION','Admin overview','Manage organizations, users, data integrations, AI services, sensors, billing, and governance.','<button class="primary-btn">+ Invite organization</button>')}<div class="admin-banner"><div><h3>GEAI Control Plane</h3><p>Production environment · eu-central · version 1.8.2</p></div><span class="tag">● All services operational</span></div><div class="kpi-grid">${kpi('Organizations','18','+2 this month','◫')}${kpi('Active users','247','92% 30-day active','♙')}${kpi('Assets managed','1,684','248.6 MW represented','◇')}${kpi('Platform uptime','99.98%','Last 30 days','◉')}</div><div class="grid-2"><div class="card"><div class="card-head"><div><h3>System activity</h3><p>Recent administrative and automated events</p></div></div><div class="activity"><div class="activity-item"><span class="activity-dot"></span><div><strong>Nova Energy added 14 solar inverters</strong><small>Asset import · 6 minutes ago</small></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>Forecast model v4.8 promoted to production</strong><small>AI registry · 32 minutes ago</small></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>7 new users accepted workspace invitations</strong><small>Identity · 1 hour ago</small></div></div><div class="activity-item"><span class="activity-dot"></span><div><strong>SCADA connector recovered automatically</strong><small>Integration health · 2 hours ago</small></div></div></div></div><div class="card"><div class="card-head"><div><h3>Service health</h3><p>Core platform components</p></div></div>${service('API gateway','99.99%','Healthy')}${service('Time-series ingestion','99.98%','Healthy')}${service('AI inference','99.97%','Healthy')}${service('Weather fusion','99.96%','Healthy')}${service('Notification service','99.99%','Healthy')}</div></div>`}
const service=(a,b,c)=>`<div class="setting-row"><div><strong>${a}</strong><small>${b} uptime · 30d</small></div><span class="tag">${c}</span></div>`;
function organizations(){return genericTablePage('TENANCY','Organizations','Manage customer workspaces, plans, asset limits, and account status.','Customer organizations',`<tr><td class="name-cell">Nova Energy</td><td>Enterprise</td><td>42</td><td>152.2 MW</td><td>68</td><td><span class="tag">Active</span></td></tr><tr><td class="name-cell">Silk Road Solar</td><td>Pro</td><td>18</td><td>18.6 MW</td><td>24</td><td><span class="tag">Active</span></td></tr><tr><td class="name-cell">GreenHome Installers</td><td>Pro</td><td>25</td><td>4.8 MW</td><td>16</td><td><span class="tag">Active</span></td></tr><tr><td class="name-cell">Demo Utility</td><td>Trial</td><td>3</td><td>8 MW</td><td>7</td><td><span class="tag orange">Trial</span></td></tr>`,['Organization','Plan','Sites','Capacity','Users','Status']);}
function users(){return genericTablePage('IDENTITY & ACCESS','Users & roles','Enterprise RBAC for operators, engineers, managers, installers, and administrators.','Users',`<tr><td class="name-cell">Khojiakbar Botirov</td><td>Nova Energy</td><td>Portfolio Operator</td><td>MFA enabled</td><td>2 min ago</td><td><span class="tag">Active</span></td></tr><tr><td class="name-cell">Aziza Karimova</td><td>Nova Energy</td><td>Asset Manager</td><td>MFA enabled</td><td>18 min ago</td><td><span class="tag">Active</span></td></tr><tr><td class="name-cell">Timur Saidov</td><td>Silk Road Solar</td><td>Technician</td><td>Password</td><td>Yesterday</td><td><span class="tag">Active</span></td></tr>`,['User','Organization','Role','Security','Last active','Status']);}
function assetsAdmin(){return genericTablePage('MASTER DATA','Asset registry','Global registry of customer sites, physical assets, telemetry IDs, and ownership.','Assets',`<tr><td class="name-cell">INV-SAM-014</td><td>Solar inverter</td><td>Samarkand Solar</td><td>Nova Energy</td><td>500 kW</td><td><span class="tag">Online</span></td></tr><tr><td class="name-cell">WTG-NAV-007</td><td>Wind turbine</td><td>Navoi Wind</td><td>Nova Energy</td><td>4.2 MW</td><td><span class="tag orange">Attention</span></td></tr><tr><td class="name-cell">BESS-TAS-002</td><td>Battery rack</td><td>Tashkent Hybrid</td><td>Nova Energy</td><td>2.5 MWh</td><td><span class="tag">Online</span></td></tr>`,['Asset ID','Type','Site','Organization','Rating','Status']);}
function integrations(){return `${pageHead('DATA PLATFORM','Data integrations','Connect SCADA, meters, OEM APIs, BMS, IoT gateways, and external weather providers.','<button class="primary-btn">+ Add connector</button>')}<div class="grid-3">${integrationCard('MQTT / IoT','2.18M msg/day','128 devices','Healthy')}${integrationCard('OPC UA / SCADA','14.8k tags','3 gateways','Healthy')}${integrationCard('Modbus TCP','684 registers','7 gateways','Healthy')}${integrationCard('Weather APIs','4 providers','Multi-source fusion','Healthy')}${integrationCard('Smart meters','86 meters','15-min intervals','Healthy')}${integrationCard('OEM APIs','4 vendors','Solar + wind','1 warning')}</div>`}
const integrationCard=(a,b,c,d)=>`<div class="card"><div class="card-head"><h3>${a}</h3><span class="tag ${d.includes('warning')?'orange':''}">${d}</span></div><strong style="font-size:22px">${b}</strong><p class="muted" style="font-size:10px">${c}</p><button class="secondary-btn wide">Configure</button></div>`;
function models(){return genericTablePage('MLOPS','AI model registry','Version, evaluate, deploy, and monitor production forecasting and diagnostic models.','Production models',`<tr><td class="name-cell">Generation Forecast v4.8</td><td>Forecasting</td><td>3.7% MAE</td><td>All portfolios</td><td>9 Aug 2026</td><td><span class="tag">Production</span></td></tr><tr><td class="name-cell">Solar Anomaly v3.2</td><td>Diagnostics</td><td>96.8% precision</td><td>Solar assets</td><td>5 Aug 2026</td><td><span class="tag">Production</span></td></tr><tr><td class="name-cell">Wind Curve v2.9</td><td>Diagnostics</td><td>94.1% precision</td><td>Wind assets</td><td>2 Aug 2026</td><td><span class="tag">Production</span></td></tr>`,['Model','Task','Quality','Scope','Updated','Stage']);}
function sensorFleet(){return genericTablePage('IOT ADMIN','Sensor fleet','Provision, monitor, update, and troubleshoot GEAI environmental sensors and gateways.','GEAI devices',`<tr><td class="name-cell">S1-014</td><td>GEAI-S1</td><td>Samarkand Solar</td><td>5 sec</td><td>91%</td><td><span class="tag">Online</span></td></tr><tr><td class="name-cell">S1-009</td><td>GEAI-S1</td><td>Bukhara Rooftop</td><td>30 sec</td><td>18%</td><td><span class="tag orange">Low battery</span></td></tr><tr><td class="name-cell">GW-NAV-01</td><td>GEAI Gateway</td><td>Navoi Wind</td><td>stream</td><td>AC</td><td><span class="tag">Online</span></td></tr>`,['Device','Model','Site','Cadence','Power','Status']);}
function alerts(){return `${pageHead('POLICY ENGINE','Alert policies','Control detection thresholds, escalation rules, channels, and maintenance triggers.','<button class="primary-btn">+ New policy</button>')}<div class="card">${setting('Critical inverter fault','Immediate · email, SMS, in-app',true)}${setting('Solar underperformance > 5%','15-minute persistence window',true)}${setting('Wind power-curve deviation > 6%','30-minute persistence window',true)}${setting('IoT sensor battery < 20%','Daily summary',true)}${setting('Forecast uncertainty > 15%','Notify portfolio operators',false)}</div>`}
function systemHealth(){return `${pageHead('OBSERVABILITY','System health','Availability, latency, queues, ingestion, AI inference, and platform dependencies.','')}<div class="kpi-grid">${kpi('API p95 latency','184 ms','↓ 12 ms vs 24h','↯')}${kpi('Ingestion rate','27.4k/s','31% headroom','⇄')}${kpi('AI inference p95','1.8 sec','Within 3s SLO','✦')}${kpi('Error rate','0.021%','Below 0.1% SLO','◎')}</div><div class="grid-2"><div class="card"><div class="card-head"><h3>Core services</h3></div>${service('API gateway','99.99%','Healthy')}${service('Telemetry ingestion','99.98%','Healthy')}${service('Forecasting service','99.97%','Healthy')}${service('Vector / AI knowledge service','99.98%','Healthy')}</div><div class="card"><div class="card-head"><h3>Data queues</h3></div>${service('MQTT telemetry','12 ms lag','Healthy')}${service('SCADA ingestion','34 ms lag','Healthy')}${service('Weather refresh','2 min age','Healthy')}${service('Report jobs','3 pending','Healthy')}</div></div>`}
function billing(){return genericTablePage('COMMERCIAL','Plans & billing','Manage subscriptions, asset limits, enterprise contracts, and invoices.','Subscriptions',`<tr><td class="name-cell">Nova Energy</td><td>Enterprise</td><td>Custom</td><td>42</td><td>Annual</td><td><span class="tag">Current</span></td></tr><tr><td class="name-cell">Silk Road Solar</td><td>Pro</td><td>€149/mo</td><td>18 / 25</td><td>Monthly</td><td><span class="tag">Current</span></td></tr><tr><td class="name-cell">GreenHome Installers</td><td>Pro</td><td>€149/mo</td><td>25 / 25</td><td>Monthly</td><td><span class="tag orange">Limit reached</span></td></tr>`,['Customer','Plan','Rate','Sites','Cycle','Status']);}
function audit(){return genericTablePage('GOVERNANCE','Audit log','Immutable trail of user actions, role changes, configuration updates, and system events.','Audit events',`<tr><td>03:07:41</td><td class="name-cell">admin@geai.energy</td><td>MODEL_PROMOTED</td><td>Generation Forecast v4.8</td><td>185.22.xx.xx</td><td><span class="tag">Success</span></td></tr><tr><td>02:51:12</td><td class="name-cell">k.botirov@nova.energy</td><td>REPORT_EXPORTED</td><td>Portfolio / July 2026</td><td>95.216.xx.xx</td><td><span class="tag">Success</span></td></tr><tr><td>02:43:08</td><td class="name-cell">system</td><td>CONNECTOR_RESTARTED</td><td>SCADA-NAV-01</td><td>internal</td><td><span class="tag">Success</span></td></tr>`,['Time','Actor','Action','Resource','Source','Result']);}
function adminSettings(){return `${pageHead('CONFIGURATION','Platform settings','Global security, retention, AI, integration, and tenant defaults.','')}<div class="grid-2"><div class="card"><div class="card-head"><h3>Security defaults</h3></div>${setting('Require MFA for admins','Enforced platform-wide',true)}${setting('SSO for Enterprise tenants','SAML / OIDC available',true)}${setting('Session timeout','12 hours',true)}${setting('IP allow-list support','Per organization',true)}</div><div class="card"><div class="card-head"><h3>AI & data</h3></div>${setting('AI explanations','Include evidence + confidence',true)}${setting('Telemetry retention','24 months hot storage',true)}${setting('Anonymized model feedback','Opt-in per tenant',false)}${setting('Automatic model rollback','On SLO regression',true)}</div></div>`}

const pageMap={overview,sites,forecast,diagnostics,maintenance,iot,expert,advisor,reports,settings,'admin-overview':adminOverview,organizations,users,assets:assetsAdmin,integrations,models,'sensor-fleet':sensorFleet,alerts,'system-health':systemHealth,billing,audit,'admin-settings':adminSettings};

function renderNav(){const items=state.role==='admin'?navAdmin:navUser;const nav=document.getElementById('nav');nav.innerHTML=items.map(item=>item.length===1?`<div class="nav-section">${item[0]}</div>`:`<div class="nav-item ${state.page===item[0]?'active':''}" data-page="${item[0]}"><span class="nav-icon">${item[1]}</span><span>${item[2]}</span>${item[3]?`<span class="nav-badge">${item[3]}</span>`:''}</div>`).join('');nav.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>setPage(el.dataset.page));}
function setPage(page){state.page=page;renderNav();document.getElementById('content').innerHTML=(pageMap[page]||overview)();document.getElementById('breadcrumb').textContent=`${state.role==='admin'?'Administration':'Platform'} / ${document.querySelector('.nav-item.active span:nth-child(2)')?.textContent||'Overview'}`;document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
window.toast=toast;window.setPage=setPage;

function login(role='user'){
  state.role=role;state.page=role==='admin'?'admin-overview':'overview';
  document.getElementById('login-screen').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');
  document.getElementById('profile-name').textContent=role==='admin'?'GEAI Administrator':'Khojiakbar Botirov';
  document.getElementById('profile-role').textContent=role==='admin'?'Platform Admin':'Portfolio Operator';
  document.getElementById('profile-avatar').textContent=role==='admin'?'GA':'KB';
  renderNav();setPage(state.page);localStorage.setItem('geai-demo-role',role);
}

document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault();login(document.getElementById('email').value.includes('admin')?'admin':'user')});
document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>{const role=b.dataset.demo;document.getElementById('email').value=role==='admin'?'admin@geai.energy':'operator@geai.energy';login(role)}));
document.getElementById('toggle-password').onclick=()=>{const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';document.getElementById('toggle-password').textContent=p.type==='password'?'Show':'Hide'};
document.getElementById('mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.getElementById('sidebar-collapse').onclick=()=>document.querySelector('.sidebar').classList.remove('open');
document.getElementById('profile-menu').onclick=()=>{if(confirm('Switch workspace? OK = Admin, Cancel = Operator'))login(state.role==='admin'?'user':'admin')};
